- hosts: web
  tasks:
    - name: deploy jar
      copy: 
        src: /var/lib/jenkins/workspace/spring-petclinic_main/target/spring-petclinic-2.4.2.jar
        dest: /home/vagrant/spring-petclinic-2.4.2.jar